spring:
  profiles:
    active: portal
  application:
    name: spring-laboratory
  jackson:
    time-zone: GMT+8
    default-property-inclusion: non_null
  security:
    user:
      name: admin
      password: admin
      roles:
        - ADMIN
  thymeleaf:
    prefix: classpath:/templates/views/
    cache: false # Production environment enabled
  datasource:
    name: THRAEX-DB
#    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/thraex-admin
    username: root
    password: mysql
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 1024MB

server:
  error:
    whitelabel:
      enabled: false

mybatis-plus:
  global-config:
    db-config:
      id-type: assign_uuid
      table-prefix: tbl_

logging:
  level:
    org.thraex.platform.mapper: debug

thraex:
  mvc:
    webjars: classpath:/META-INF/resources/webjars
    resources:
      - paths: ${thraex.file.access-prefix}/**
        locations: file://${thraex.file.directory}/
#      - paths:
#          - /favicon.ico
#          - /assets/**
#        locations: classpath:/templates/assets/
      - paths: /assets/**
        locations: classpath:/templates/assets/
      - paths: /favicon.ico
        locations: ${thraex.favicon:classpath:/templates/assets/}
      - paths: /vue/**
        locations: ${thraex.mvc.webjars}/vue/2.6.11/
      - paths: /AdminLTE/**
        locations: ${thraex.mvc.webjars}/AdminLTE/3.0.5/
      - paths: /element-ui/**
        locations: ${thraex.mvc.webjars}/element-ui/2.13.2/
      - paths: /axios/**
        locations: ${thraex.mvc.webjars}/axios/0.19.2/
      - paths: /qs/**
        locations: ${thraex.mvc.webjars}/qs/6.9.4/
    views:
      dashboard: dashboard
      menu: menu
      dict: dict
      user: user
      role: role
      grant: grant
      profile: profile
      login: login
  site:
    permits:
      - /auth/crypto
      - /AdminLTE/**
      - /assets/images/**
  file:
    directory: ${user.home}/thraex-files
    access-prefix: /assets/files
  user:
    init-password: 111111
